### ISSUE TITLE
Access old version documentations?

### ISSUE THREAD

**Issue by xfudox** [orchidsoftware/orchid.software#100]
I've recently installed Laravel 7 + Orchid 7 due server requirements, but i cannot figure out how to access Orchid 7 documentations.

The [Documentation section](https://orchid.software/en/docs/) seems not to let the user choose the platform version, so i suppose the docs displayed are for the latest release, i.e.: 9.x.

Is there any way to access Orchid 7.x documentation?

**Comment by tabuna** [comment]
Hi @xfudox,  you can use tag and access. For example, [here are the docs for version 7](https://github.com/orchidsoftware/orchid.software/tree/7.0/source/en/docs
), but I highly recommend using the current versions.
