### ISSUE TITLE
How could I remove the "Adminstrator" word in the sidebar "Profile Menu"?

### ISSUE THREAD

**Issue by alash3al** [orchidsoftware/orchid.software#57]

**Comment by tabuna** [comment]
You can change this in your model representatives.

https://github.com/orchidsoftware/platform/blob/ac65d0ce4037e938c57fb7ee2c0d9886782f5476/install-stubs/Orchid/Presenters/UserPresenter.php#L35 

in details: https://orchid.software/en/docs/presenters/

**Comment by alash3al** [comment]
Thank you @tabuna
