### ISSUE TITLE
Создание блога по документации

### ISSUE THREAD

**Issue by PSalador** [orchidsoftware/orchid.software#6]
[Создание блога](https://orchid.software/ru/docs/tutorial_blog/)

1. Переделать под SASS?
2. Отображение виджета - добавить путь /views/partials/menu.blade.php
3. По адресу /app/Core/Behaviors/Many заменить на /app/Behaviors/Many
4.  Переделать под 2.1
5.  Можно регистрировать в платформе config/platform  - странно очистка конфига  в dashboard/systems/cache не помогает, а php artisan config:cache норм работает.
6. Роутинг неправильно:
```
$router->get('/','BlogController@index');
$router->get('/{blog}','BlogController@show')
    ->where('blog','^(?!dashboard).*$')
    ->name('blog.post');
```
7.   Роут blog, в RouteServiceProvider в  function map()
8. если в каталог resource то установить
```
npm install cross-env 
npm install laravel-mix
npm install popper.js
npm install jquery
npm install axios
npm install vue

npm run prod
```
9. Что-то пока не получается вывести данные - думаю что-то с локалями getContent.

**Comment by tabuna** [comment]
1. Там даже уже эта тема на bs4 вышла
1. Не понял
1. Да я думаю под 2.1 нужно менять
1. Да я думаю под 2.1 нужно менять
1. Думаю, что мы уберём чистку кэша вообще из веб интерфейса
1. Почему не правильный? Вроде валидный
1. Да менять
1. А зачем устанавливать их?
1. Нужно смотреть ;)

**Comment by PSalador** [comment]
2. Добавить в документацию, что нужно создать файл /views/partials/menu.blade.php
6. В документации.
8. Надо смотреть - я в стандартный app.js снизу дописал, какие ошибки по пакетам были сюда записал, наверно что-то убрать нужно, но и из bootstrap.js придется убрать. Может в описании сразу в public кидать?
9. Вижу трайт по getContent подключения локали MultiLanguage.php, но куда его подключить.

**Comment by PSalador** [comment]
6. Я понял в документации это не ошибка, а где-то он думает что это email и вместо BlogController@index выдает [email protected], сейчас в документации так:
```
$router->get('/','[email protected]');
$router->get('/{blog}','[email protected]')
    ->where('blog','^(?!dashboard).*$')
    ->name('blog.post');
```

**Comment by tabuna** [comment]
Да это cloudflare заменяет. Попробую отключить.

**Comment by PSalador** [comment]
10. Поиск бы какой-нибудь сделать, а то как категории сделать искал искал да не нашел. Потом случайно в записи зашел.
11. [Теги.Настройка](https://orchid.software/ru/docs/tags/#nastroyka) непонятное предложение:
> Это очень полезный метод при запуске обновления на субъектов, и вы не хотите иметь дело с проверками,

**Comment by tabuna** [comment]
Поиск уже в [планах](https://github.com/orchidsoftware/platform/issues/465#issuecomment-362430500)
По тегам если несложно переформулируй, что бы было проще.

**Comment by PSalador** [comment]
По тегам я не понимаю, что там написано, я бы вес абзац написал так:

> Метод  setTags() заменяет все теги на предложенные. Если вторым параметром использовать 'slug' то (незнаю, для чего он).
