### ISSUE TITLE
Orchid.software reload issue

### ISSUE THREAD

**Issue by scream1301** [orchidsoftware/orchid.software#7]
I have found a little issue with the homepage of orchid.software
If you load the homepage of https://orchid.software/ for the first time, everything works fine,
but if you reload the page again it shows 404 page not found

**Comment by tabuna** [comment]
Oh, this is a big problem, as many people work with the website.

Thank you for paying attention to this, I assume that the mistake is in determining the [language](https://github.com/orchidsoftware/orchid.software/blob/master/app/Http/Middleware/SetDefaultLocaleForUrls.php).

If not difficult, please tell the language installed in your browser. Thanks again.

**Comment by tabuna** [comment]
I updated it, the error should not happen again.

**Comment by scream1301** [comment]
Sure no problem.
Great to hear that. Yes it works for me too.
