### ISSUE TITLE
Quickstart -Email sender

### ISSUE THREAD

**Issue by rabol** [orchidsoftware/orchid.software#86]
Hi

I'm trying to get started with Orchid, so I started with the Email sender example

One thing that I noticed was that the command: 

`php artisan orchid:screen EmailSenderScreen`

Generate the file, but it add

`use Orchid\Screen\Layout;
`

now, if one simply copy past the code in the methods, then you will get an error that Layout::rows does not exists.

This issue here is: is this a documentation error or a 'scaffolding' error ?

e.g. the default PlatformScreen uses:

`use Orchid\Support\Facades\Layout;`

instead of the on from the make command:

`use Orchid\Screen\Layout;`

**Comment by tabuna** [comment]
Hey @rabol. I made fixes to the scaffolding. This could really confuse new users.

Now there will be no more indication `use Orchid\Screen\Layout;`.
