### ISSUE TITLE
How to build / re-build the assets

### ISSUE THREAD

**Issue by rabol** [orchidsoftware/orchid.software#90]
It would be beneficial to have some guidance / documentation how to build the assets that is used.

It is especially useful in development as it is difficult to read / debug the minified versions of js and css

**Comment by tabuna** [comment]
Hey @rabol. Do you mean this?

![image](https://user-images.githubusercontent.com/5102591/104686363-1d707500-570e-11eb-968e-5db33832b8bd.png)

This is done in the same way as in the Laravel app (via Laravel mix)

**Comment by rabol** [comment]
yes, but for the platform package or the crud package

e.g. the vendor.js in the /public/js folder

**Comment by tabuna** [comment]
CRUD package has a no-js code. Fully relies on the [platform](https://github.com/orchidsoftware/platform).
To rebuild js for development and further sending PR, you can install the package following the instructions on this page
https://orchid.software/en/community/contributors/ (Development Installation). This will use the same `npm` commands

**Comment by rabol** [comment]
Thanks
